
export const ADD_TO_CART_REQUEST =" ADD_TO_CART_REQUEST";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM = "REMOVE_SINGLE_PRODUCT_FROM_CART";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const EMPTY_CART_REQUEST = " EMPTY_CART_REQUEST";
export const EMPTY_CART="EMPTY_CART";
export const EMPTY_CART_FAIL = " EMPTY_CART_FAIL";

export const EMPTY_CART_FROM_CLIENT_REQUEST = " EMPTY_CART_FROM_CLIENT_REQUEST";
export const EMPTY_CART_FROM_CLIENT="EMPTY_CART_FROM_CLIENT";
export const EMPTY_CART_FROM_CLIENT_FAIL = " EMPTY_CART_FROM_CLIENT_FAIL";

export const GET_CART_REQUEST ="GET_CART_REQUEST";
export const GET_CART ="GET_CART";
export const GET_CART_FAIL ="GET_CART_FAIL";

export const CLEAR_ERRORS ="CLEAR_ERRORS";