export const ALL_COUPAN_REQUEST = "ALL_COUPAN_REQUEST";
export const ALL_COUPAN_SUCCESS = "ALL_COUPAN_SUCCESS";
export const ALL_COUPAN_FAIL = "ALL_COUPAN_FAIL";

export const NEW_COUPAN_REQUEST = "NEW_COUPAN_REQUEST";
export const NEW_COUPAN_SUCCESS = "NEW_COUPAN_SUCCESS";
export const NEW_COUPAN_RESET = "NEW_COUPAN_RESET";
export const NEW_COUPAN_FAIL = "NEW_COUPAN_FAIL";

export const UPDATE_COUPAN_REQUEST = "UPDATE_COUPAN_REQUEST";
export const UPDATE_COUPAN_SUCCESS = "UPDATE_COUPAN_SUCCESS";
export const UPDATE_COUPAN_RESET = "UPDATE_COUPAN_RESET";
export const UPDATE_COUPAN_FAIL = "UPDATE_COUPAN_FAIL";

export const DELETE_COUPAN_REQUEST = "DELETE_COUPAN_REQUEST";
export const DELETE_COUPAN_SUCCESS = "DELETE_COUPAN_SUCCESS";
export const DELETE_COUPAN_RESET = "DELETE_COUPAN_RESET";
export const DELETE_COUPAN_FAIL = "DELETE_COUPAN_FAIL";

export const COUPAN_DETAILS_REQUEST = "COUPAN_DETAILS_REQUEST";
export const COUPAN_DETAILS_SUCCESS = "COUPAN_DETAILS_SUCCESS";
export const COUPAN_DETAILS_FAIL = "COUPAN_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
